language: python
sudo: false
branches:
  only:
    - master
addons:
  postgresql: "9.4"
python:
  - 2.7
before_script:
  - psql -c 'CREATE DATABASE helpothers;' -U postgres
  - cp helpothers/secrets.py.example helpothers/secrets.py
install:
  - pip install -r requirements.txt
script:
  - ./manage.py test
